# Generated by Django 3.2 on 2023-08-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20230812_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestConfig',
        ),
    ]
