# Generated by Django 4.1.3 on 2023-09-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_delete_bestconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
