version: "3.8"
services:
  frontend:
    build:
      context: ./frontend/v1-front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontend-backend-network
  backend:
    build:
      context: ./backend/projectV1
      dockerfile: Dockerfile 
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - frontend
    networks:
      - frontend-backend-network
networks:
  frontend-backend-network:
    driver: bridge