# Generated by Django 3.2 on 2023-08-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ray_ai', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestConfig',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
