# Generated by Django 3.2 on 2023-08-12 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0003_delete_bestconfig'),
        ('ray_ai', '0002_auto_20230812_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_estimators', models.PositiveIntegerField()),
                ('accuracy', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user')),
            ],
        ),
    ]
