# Generated by Django 4.1.3 on 2023-09-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ray_ai', '0003_bestconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestconfig',
            name='user',
        ),
    ]
