import React from "react";
import AITextDisplay from "./AITextDisplay";

const AIOutput = () => {
  const aiText =
    "This is some text generated by the AI. It is limited to 50 words for clarity. This is some text generated by the AI. It is limited to 50 words for clarity. This is some text generated by the AI. It is limited to 50 words for clarity. This is some text generated by the AI. It is limited to 50 words for clarity. This is some text generated by the AI. It is limited to 50 words for clarity. This is some text generated by the AI. It is limited to 50 words for clarity. This is some text generated by the AI. It is limited to 50 words for clarity. ";

  const handleNext = () => {
    console.log("Next button clicked");
    // Handle the next button click here
  };

  return (
    <div>
      <AITextDisplay aiText={aiText} onNext={handleNext} />
    </div>
  );
};

export default AIOutput;
